#ifndef TERMSEQUEL_COLUMN_H
#define TERMSEQUEL_COLUMN_H

#define SYSTEM_COLUMN_NAME_STRING "NAME"
#define SYSTEM_COLUMN_SIZE_STRING "SIZE"
#define SYSTEM_COLUMN_TYPE_STRING "TYPE"
#define SYSTEM_COLUMN_OWNER_ID_STRING "OWNER_ID"
#define SYSTEM_COLUMN_OWNER_NAME_STRING "OWNER_NAME"
#define SYSTEM_COLUMN_CREATE_DATE_STRING "CREATE_DATE"
#define SYSTEM_COLUMN_MODIFY_DATE_STRING "MODIFY_DATE"
#define SYSTEM_COLUMN_GROUP_ID_STRING "GROUP_ID"
#define SYSTEM_COLUMN_GROUP_NAME_STRING "GROUP_NAME"
#define SYSTEM_COLUMN_DEPTH_LEVEL_STRING "DEPTH_LEVEL"
#define SYSTEM_COLUMN_RELATIVE_PATH_STRING "RELATIVE_PATH"
#define SYSTEM_COLUMN_OWNER_PERMISSION_STRING "OWNER_PERMISSION"
#define SYSTEM_COLUMN_GROUP_PERMISSION_STRING "GROUP_PERMISSION"

#define DATE_PATTERN "%Y-%m-%dT%H:%M:%S"

#endif
