#include "termsequel/frontend/token.h"

const char* TOKEN_NAMES[] = { "INVALID",
                              "SELECT",
                              "INSERT",
                              "DELETE",
                              "UPDATE",
                              "FROM",
                              "WHERE",
                              "AND",
                              "OR",
                              "IDENTIFIER",
                              "COMMA",
                              "STAR",
                              "NUMBER",
                              "STRING",
                              "LEFT_PARENTHESIS",
                              "RIGHT_PARENTHESIS",
                              "PLUS",
                              "MINUS",
                              "EQUAL",
                              "GREATER_THAN_OR_EQUAL",
                              "LESS_THAN_OR_EQUAL",
                              "NOT_EQUAL",
                              "GREATER_THAN",
                              "LESS_THAN",
                              "UPPER",
                              "LOWER",
                              "DIVISION",
                              "MODULE",
                              "MAX",
                              "MIN",
                              "AVG",
                              "BOOLEAN",
                              "EOF",
                              "AS",
                              "ORDER",
                              "BY",
                              "ASC",
                              "DESC",
                              "LIMIT",
                              "LIKE",
                              "GROUP",
                              "NOT",
                              "DATE" };

const char* TOKEN_CLASS_NAMES[] = {
    "INVALID", "KEYWORD", "SPECIAL", "BINARY_RELATIONAL_OPERATOR", "LOGICAL_OPERATOR", "UNARY_ARITHMETIC_OPERATOR", "BINARY_ARITHMETIC_OPERATOR", "LITERAL", "FUNCTION", "UNARY_RELATIONAL_OPERATOR" };