name: C/C++ CI

on:
  push:
    branches:
      - main

jobs:
  compile_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create build directory
      run: mkdir build && cd build
    - name: Run CMake
      run: cmake ../ && cmake --build .
  compile_windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Create build directory
      run: mkdir build && cd build
    - name: Run CMake
      run: cmake ../ && cmake --build .
