name: "pre-release"

on:
  push:
    branches:
      - "main"

env:
  BUILD_TYPE: Release

jobs:

  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v1.0.1
        with:
          sources: "src/*.cpp, include/*.hpp"
          style: "LLVM"

  build:
    needs: code-style
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to branch
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Rename binaries
      run:  mv ${{github.workspace}}/build/executable/termsequel termsequel-linux-amd64
      shell: bash

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: termsequel-linux-amd64
        retention-days: 3


  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v2
      with:
        name: binaries
    - name: Get binary version
      run: chmod +x termsequel-linux-amd64 && ./termsequel-linux-amd64 --help | tail -n1 | awk ' { print "BIN_VERSION="$2 } ' >> $GITHUB_ENV
      shell: bash

    - name: Automatic Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: v${{env.BIN_VERSION}}-rc
        prerelease: true
        title: "Termsequel Release Candidate"
        files: |
          termsequel-linux-amd64
