name: "pre-release"

on:
  push:
    branches:
      - "release"

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to branch
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Get only the executable
      run: mv ${{github.workspace}}/build/executable/termsequel termsequel-linux-amd64

    - name: Cache Linux executable
      uses: actions/cache@v2
      with:
        path: termsequel-linux-amd64
        key: linux-binary


  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - name: Restore Cache Linux
      uses: actions/cache@v2
      with:
        path: termsequel-linux-amd64
        key: linux-binary
    - name: Get binary version
      run: ./termsequel-linux-amd64 -h | tail -n1 | awk ' { print "BIN_VERSION="$2 } ' >> $GITHUB_ENV
      shell: bash
    - name: Automatic Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: v${{env.BIN_VERSION}}-rc
        prerelease: false
        title: "Termsequel Release"
        files: |
          termsequel-linux-amd64
